workflows:
  ios_release:
    name: iOS Release
    environment:
      flutter: 3.10.5
      xcode: 16.2
    scripts:
      - name: Clean Flutter
        script: flutter clean

      - name: Pub get
        script: flutter pub get

      - name: Remove old Pods
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          rm -rf Flutter/Flutter.framework
          rm -rf Flutter/App.framework
          cd ..

      - name: Install working CocoaPods version
        script: |
          sudo gem uninstall cocoapods -a -x || true
          sudo gem install cocoapods -v 1.12.1
          pod --version

      - name: Set FLUTTER_ROOT for subsequent steps
        script: |
          echo "export FLUTTER_ROOT=$(flutter sdk-path)" >> $CM_ENV

      - name: Precache iOS engine artifacts
        script: flutter precache --ios

      - name: Pod install
        script: |
          cd ios
          pod deintegrate || true
          pod repo update
          pod install
          cd ..

      - name: Build iOS Release
        script: flutter build ios --release --no-tree-shake-icons --verbose

    artifacts:
      - build/ios/**/*.ipa
      - build/app/outputs/**
  default_workflow:
    name: Default Workflow
    environment:
      flutter: 3.10.5
      xcode: 16.2
    scripts:
      - name: Clean Flutter
        script: flutter clean

      - name: Pub get
        script: flutter pub get

      - name: Remove old Pods
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          rm -rf Flutter/Flutter.framework
          rm -rf Flutter/App.framework
          cd ..

      - name: Install working CocoaPods version
        script: |
          sudo gem uninstall cocoapods -a -x || true
          sudo gem install cocoapods -v 1.12.1
          pod --version

      - name: Set FLUTTER_ROOT for subsequent steps
        script: |
          echo "export FLUTTER_ROOT=$(flutter sdk-path)" >> $CM_ENV

      - name: Precache iOS engine artifacts
        script: flutter precache --ios

      - name: Pod install
        script: |
          cd ios
          pod deintegrate || true
          pod repo update
          pod install
          cd ..

      - name: Build IPA with export options
        script: |
          if [ -f /Users/builder/export_options.plist ]; then
            flutter build ipa --release --no-tree-shake-icons --export-options-plist /Users/builder/export_options.plist --verbose
          else
            flutter build ios --release --no-tree-shake-icons --verbose
          fi

    artifacts:
      - build/ios/**/*.ipa
      - build/app/outputs/**
