workflows:
  ios_release:
    name: iOS Release
    environment:
      flutter: 3.10.5
      xcode: 16.2
    scripts:
      - name: Clean Flutter
        script: flutter clean

      - name: Pub get
        script: flutter pub get

      - name: Generate iOS App Icons (flutter_launcher_icons)
        script: dart run flutter_launcher_icons

      - name: Install Pillow for icon processing
        script: pip3 install --user pillow

      - name: Remove old Pods
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          rm -rf Flutter/Flutter.framework
          rm -rf Flutter/App.framework
          cd ..

      - name: Install working CocoaPods version
        script: |
          sudo gem uninstall cocoapods -a -x || true
          sudo gem install cocoapods -v 1.12.1
          pod --version

      - name: Set FLUTTER_ROOT for subsequent steps
        script: |
          echo "export FLUTTER_ROOT=$(flutter sdk-path)" >> $CM_ENV

      - name: Precache iOS engine artifacts
        script: flutter precache --ios

      - name: Pod install
        script: |
          cd ios
          pod deintegrate || true
          pod repo update
          pod install
          cd ..

      - name: Fix iOS App Icons (remove alpha)
        script: |
          ICONSET_DIR="ios/Runner/Assets.xcassets/AppIcon.appiconset"
          if [ -d "$ICONSET_DIR" ]; then
            if command -v magick >/dev/null 2>&1; then
              for f in "$ICONSET_DIR"/*.png; do
                [ -f "$f" ] || continue
                magick "$f" -background white -alpha remove -alpha off -flatten "$f"
              done
            else
              python3 - << 'PY'
import os
from PIL import Image
iconset_dir = "ios/Runner/Assets.xcassets/AppIcon.appiconset"
for fname in os.listdir(iconset_dir):
    if fname.lower().endswith('.png'):
        p = os.path.join(iconset_dir, fname)
        im = Image.open(p)
        has_alpha = (im.mode in ('RGBA','LA')) or (im.mode=='P' and 'transparency' in im.info)
        if has_alpha:
            if im.mode != 'RGBA':
                im = im.convert('RGBA')
            bg = Image.new('RGB', im.size, (255,255,255))
            bg.paste(im, mask=im.split()[3])
            bg.save(p, 'PNG')
PY
            fi
          fi

      - name: Verify iOS Marketing Icon has no alpha
        script: |
          ICON="ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png"
          if [ -f "$ICON" ]; then
            sips -g hasAlpha "$ICON" | grep -q "no" && echo "Marketing icon has no alpha" || { echo "Alpha still present"; exit 1; }
          fi

      - name: Build iOS Release
        script: flutter build ios --release --no-tree-shake-icons --verbose

    artifacts:
      - build/ios/**/*.ipa
      - build/app/outputs/**
  default_workflow:
    name: Default Workflow
    environment:
      flutter: 3.10.5
      xcode: 16.2
    scripts:
      - name: Clean Flutter
        script: flutter clean

      - name: Pub get
        script: flutter pub get

      - name: Generate iOS App Icons (flutter_launcher_icons)
        script: dart run flutter_launcher_icons

      - name: Install Pillow for icon processing
        script: pip3 install --user pillow

      - name: Remove old Pods
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          rm -rf Flutter/Flutter.framework
          rm -rf Flutter/App.framework
          cd ..

      - name: Install working CocoaPods version
        script: |
          sudo gem uninstall cocoapods -a -x || true
          sudo gem install cocoapods -v 1.12.1
          pod --version

      - name: Set FLUTTER_ROOT for subsequent steps
        script: |
          echo "export FLUTTER_ROOT=$(flutter sdk-path)" >> $CM_ENV

      - name: Precache iOS engine artifacts
        script: flutter precache --ios

      - name: Pod install
        script: |
          cd ios
          pod deintegrate || true
          pod repo update
          pod install
          cd ..

      - name: Fix iOS App Icons (remove alpha)
        script: |
          ICONSET_DIR="ios/Runner/Assets.xcassets/AppIcon.appiconset"
          if [ -d "$ICONSET_DIR" ]; then
            if command -v magick >/dev/null 2>&1; then
              for f in "$ICONSET_DIR"/*.png; do
                [ -f "$f" ] || continue
                magick "$f" -background white -alpha remove -alpha off -flatten "$f"
              done
            else
              python3 - << 'PY'
import os
from PIL import Image
iconset_dir = "ios/Runner/Assets.xcassets/AppIcon.appiconset"
for fname in os.listdir(iconset_dir):
    if fname.lower().endswith('.png'):
        p = os.path.join(iconset_dir, fname)
        im = Image.open(p)
        has_alpha = (im.mode in ('RGBA','LA')) or (im.mode=='P' and 'transparency' in im.info)
        if has_alpha:
            if im.mode != 'RGBA':
                im = im.convert('RGBA')
            bg = Image.new('RGB', im.size, (255,255,255))
            bg.paste(im, mask=im.split()[3])
            bg.save(p, 'PNG')
PY
            fi
          fi

      - name: Verify iOS Marketing Icon has no alpha
        script: |
          ICON="ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png"
          if [ -f "$ICON" ]; then
            sips -g hasAlpha "$ICON" | grep -q "no" && echo "Marketing icon has no alpha" || { echo "Alpha still present"; exit 1; }
          fi

      - name: Build IPA with export options
        script: |
          if [ -f /Users/builder/export_options.plist ]; then
            flutter build ipa --release --no-tree-shake-icons --export-options-plist /Users/builder/export_options.plist --verbose
          else
            flutter build ios --release --no-tree-shake-icons --verbose
          fi

    artifacts:
      - build/ios/**/*.ipa
      - build/app/outputs/**
