workflows:
  ios_release:
    name: iOS Release
    environment:
      flutter: 3.10.5
      xcode: 16.2
    scripts:
      - name: Clean Flutter
        script: flutter clean

      - name: Pub get
        script: flutter pub get

      - name: Remove old Pods
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          rm -rf Flutter/Flutter.framework
          rm -rf Flutter/App.framework
          cd ..

      - name: Install working CocoaPods version
        script: |
          sudo gem uninstall cocoapods -a -x || true
          sudo gem install cocoapods -v 1.12.1
          pod --version

      - name: Precache iOS engine artifacts
        script: flutter precache --ios

      - name: Pod install
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Build iOS Release
        script: flutter build ios --release --no-tree-shake-icons

    artifacts:
      - build/ios/**/*.ipa
      - build/app/outputs/**
