workflows:
  ios_release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: 16.1
    scripts:
      - name: Flutter clean
        script: flutter clean
      - name: Install dependencies
        script: flutter pub get
      - name: CocoaPods install
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update || true
          pod install
      - name: Build iOS release (no tree shake icons)
        script: flutter build ios --release --no-tree-shake-icons
    artifacts:
      - build/ios/**/*.ipa
      - build/app/outputs/**
