platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __FILE__)

target 'Runner' do
  use_frameworks! :linkage => :static
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  flutter_additional_ios_build_settings(installer)
end
