platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

def flutter_root
  env_root = ENV['FLUTTER_ROOT']
  return env_root if env_root && File.directory?(env_root)
  begin
    which_flutter = `which flutter`.strip
    if which_flutter && which_flutter.length > 0 && File.exist?(which_flutter)
      real = File.realpath(which_flutter)
      candidate = File.expand_path('..', File.dirname(real))
      return candidate if File.directory?(candidate)
    end
  rescue => e
    puts e
  end
  generated_xcconfig = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcconfig)
    raise "#{generated_xcconfig} must exist. Run 'flutter pub get' first."
  end
  File.foreach(generated_xcconfig) do |line|
    match = line.match(/FLUTTER_ROOT\=(.*)/)
    return match[1].strip if match
  end
  raise "FLUTTER_ROOT not found in #{generated_xcconfig}"
end

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'), __FILE__)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  begin
    fr = flutter_root
    flutter_bin = File.join(fr, 'bin', 'flutter')
    system("#{flutter_bin} --version")
    system("#{flutter_bin} precache --ios")
  rescue => e
    puts e
  end
  begin
    if defined?(flutter_post_install)
      flutter_post_install(installer)
    else
      flutter_additional_ios_build_settings(installer)
    end
  rescue => e
    puts e
  end
  begin
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  rescue => e
    puts e
  end
  begin
    installer.pods_project.targets.each do |t|
      if t.name == 'Flutter'
        t.build_configurations.each do |config|
          config.build_settings['DEFINES_MODULE'] = 'YES'
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        end
      end
    end
  rescue => e
    puts e
  end
  begin
    pods_root = installer.sandbox.root.to_s
    project_dir = File.dirname(File.realpath(__FILE__))
    header_paths = []
    framework_paths = []
    Dir.glob(File.join(pods_root, 'Flutter', 'Flutter.xcframework', '**', 'Flutter.framework', 'Headers')).each do |hp|
      header_paths << hp
      framework_paths << File.dirname(hp)
    end
    # Fallback to engine artifacts under FLUTTER_ROOT if Pods path is missing
    begin
      engine_root = File.join(flutter_root, 'bin', 'cache', 'artifacts', 'engine', 'ios')
      Dir.glob(File.join(engine_root, '**', 'Flutter.framework', 'Headers')).each do |hp|
        header_paths << hp
        framework_paths << File.dirname(hp)
      end
    rescue
    end
    # Also include local ios/Flutter directory if legacy frameworks exist
    Dir.glob(File.join(project_dir, 'Flutter', '**', 'Flutter.framework', 'Headers')).each do |hp|
      header_paths << hp
      framework_paths << File.dirname(hp)
    end
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        current_headers = config.build_settings['HEADER_SEARCH_PATHS'] || "$(inherited)"
        current_frameworks = config.build_settings['FRAMEWORK_SEARCH_PATHS'] || "$(inherited)"
        current_ldflags = config.build_settings['OTHER_LDFLAGS'] || "$(inherited)"
        headers = "#{current_headers} $(PODS_ROOT)/Headers/Public #{header_paths.join(' ')} #{project_dir}/Flutter"
        frameworks = "#{current_frameworks} $(PODS_ROOT)/** #{framework_paths.join(' ')} $(FLUTTER_ROOT)/bin/cache/artifacts/engine/ios/**"
        config.build_settings['HEADER_SEARCH_PATHS'] = headers
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] = frameworks
        config.build_settings['OTHER_LDFLAGS'] = "#{current_ldflags} -framework Flutter"
      end
    end
  rescue => e
    puts e
  end
  begin
    installer.aggregate_targets.each do |aggregate_target|
      if aggregate_target.name == 'Pods-Runner'
        aggregate_target.user_project.targets.each do |target|
          target.build_configurations.each do |config|
            xc = aggregate_target.xcconfigs[config.name]
            if xc
              config.base_configuration_reference = xc
            end
          end
        end
      end
    end
  rescue => e
    puts e
  end
end
